apiVersion: apps/v1
kind: Deployment
metadata:
  name: safedev-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safedev-demo
  template:
    metadata:
      labels:
        app: safedev-demo
    spec:
      containers:
        - name: app
          image: demo:latest
          securityContext:
            privileged: true
